// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace backend.Entities
{
    public partial class City
    {
        public City()
        {
            University = new HashSet<University>();
            UserCity = new HashSet<UserCity>();
        }

        public int city_id { get; set; }
        public string name { get; set; }

        public virtual ICollection<University> University { get; set; }
        public virtual ICollection<UserCity> UserCity { get; set; }
    }
}