// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace backend.Entities
{
    public partial class Club
    {
        public Club()
        {
            UniversityClub = new HashSet<UniversityClub>();
            UserClub = new HashSet<UserClub>();
        }

        public int club_id { get; set; }
        public string name { get; set; }

        public virtual ICollection<UniversityClub> UniversityClub { get; set; }
        public virtual ICollection<UserClub> UserClub { get; set; }
    }
}