// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Entities
{
    public partial class Job
    {
        public Job()
        {
            UniversityJob = new HashSet<UniversityJob>();
            UserJob = new HashSet<UserJob>();
        }

        public int job_id { get; set; }
        public string name { get; set; }

        public virtual ICollection<UniversityJob> UniversityJob { get; set; }
        public virtual ICollection<UserJob> UserJob { get; set; }
    }
}