// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace backend.Entities
{
    public partial class Subject
    {
        public Subject()
        {
            UniversitySubject = new HashSet<UniversitySubject>();
            UserSubject = new HashSet<UserSubject>();
        }

        public int subject_id { get; set; }
        public string name { get; set; }

        public virtual ICollection<UniversitySubject> UniversitySubject { get; set; }
        public virtual ICollection<UserSubject> UserSubject { get; set; }
    }
}