// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace backend.Entities
{
    public partial class UniversityCity
    {
        public int universityCity_id { get; set; }
        public int city_id { get; set; }
        public int university_id { get; set; }

        public virtual City city { get; set; }
        public virtual University university { get; set; }
    }
}