// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Entities
{
    public partial class UniversityInterest
    {
        public int universityInterest_id { get; set; }
        public int interest_id { get; set; }
        public int university_id { get; set; }

        public virtual Interest interest { get; set; }
        public virtual University university { get; set; }
    }
}