// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace backend.Entities
{
    public partial class UniversitySubject
    {
        public int universitySubject_id { get; set; }
        public int subject_id { get; set; }
        public int university_id { get; set; }

        public virtual Subject subject { get; set; }
        public virtual University university { get; set; }
    }
}