// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Entities
{
    public partial class UserSubject
    {
        public int userSubject_id { get; set; }
        public int subject_id { get; set; }
        public int user_id { get; set; }

        public virtual Subject subject { get; set; }
        public virtual User user { get; set; }
    }
}