// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace backend.Entities
{
    public partial class User
    {
        public User()
        {
            Reviews = new HashSet<Reviews>();
            UserCity = new HashSet<UserCity>();
            UserClub = new HashSet<UserClub>();
            UserInterest = new HashSet<UserInterest>();
            UserJob = new HashSet<UserJob>();
            UserMetings = new HashSet<UserMetings>();
            UserSubject = new HashSet<UserSubject>();
        }

        public int user_id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string lastName { get; set; }
        public string firstName { get; set; }
        public int? age { get; set; }
        public string role { get; set; }
        public byte[] join_date { get; set; }

        public virtual ICollection<Reviews> Reviews { get; set; }
        public virtual ICollection<UserCity> UserCity { get; set; }
        public virtual ICollection<UserClub> UserClub { get; set; }
        public virtual ICollection<UserInterest> UserInterest { get; set; }
        public virtual ICollection<UserJob> UserJob { get; set; }
        public virtual ICollection<UserMetings> UserMetings { get; set; }
        public virtual ICollection<UserSubject> UserSubject { get; set; }
    }
}