// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace backend.Entities
{
    public partial class UserMetings
    {
        public int userMeeting_id { get; set; }
        public int meeting_id { get; set; }
        public int user_id { get; set; }

        public virtual Meeting meeting { get; set; }
        public virtual User user { get; set; }
    }
}