// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace backend.Entities
{
    public partial class UserClub
    {
        public int userClub_id { get; set; }
        public int club_id { get; set; }
        public int user_id { get; set; }

        public virtual Club club { get; set; }
        public virtual User user { get; set; }
    }
}