// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace backend.Entities
{
    public partial class UserJob
    {
        public int userJob_id { get; set; }
        public int job_id { get; set; }
        public int user_id { get; set; }

        public virtual Job job { get; set; }
        public virtual User user { get; set; }
    }
}