// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace backend.Entities
{
    public partial class UserCity
    {
        public int userCity_id { get; set; }
        public int city_id { get; set; }
        public int user_id { get; set; }

        public virtual City city { get; set; }
        public virtual User user { get; set; }
    }
}