// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace backend.Entities
{
    public partial class UserInterest
    {
        public int userInterest_id { get; set; }
        public int interest_id { get; set; }
        public int user_id { get; set; }

        public virtual Interest interest { get; set; }
        public virtual User user { get; set; }
    }
}